language: python
python:
- "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# email notification
notifications:
  email:
    - ryan@boostblocks.com
# command to run tests
script: coverage run manage.py test
after_success:
    coveralls